spring.application.name=e-commerce-api

# Veritabanı Bağlantı Bilgileri
spring.datasource.url=jdbc:postgresql://localhost:5432/ecommercedb
spring.datasource.username=postgres
spring.datasource.password=mysecretpassword
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate Ayarları
# 'create' yapılarak tabloların sıfırdan zorla oluşturulması sağlanır
spring.jpa.hibernate.ddl-auto=create

# Oluşturulan SQL sorgularını konsola bastırır
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Not: hibernate.dialect satırı Hibernate 6+ otomatik tespit ettiği için kaldırılmıştır.